# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Dadan R. / %s"
og_image: /img/profile.png
author: Dadan R.
favicon: /img/profile.png
description: Mobile App Developer, Software Crafter, Solo Founder
port: 8083

# OG image
origin: https://hiperkreatif.com
og: /img/profile.png

navigation:
  header:
    - Dadan R.: /
    - Portfolio: /portfolio/
    - Contact: /contact/

  footer:
    - © Dadan R.: /

    - image: /img/github.svg
      url: //github.com/ddr137
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/ramdhani-ddr1
      alt: LinkedIn profile
      size: 22 x 22
